import{VERSION,MARKETS,CFG}from"./config.js";import{derivAPI}from"./deriv-api.js";import{snapshot}from"./indicators.js";import{explore}from"./engine1.js";import{engine2}from"./engine2.js";import{visual,manualText}from"./prediction.js";import{voice}from"./voice.js";
const $=id=>document.getElementById(id),U={};["estadoConexion","textoEstadoConexion","estadoMotor","textoEstadoMotor","estadoMemoria","botonConectar","botonDesconectar","botonEncenderMotor","botonPrediccion","mensajeControl","selectorEstrategia","selectorMercado","selectorModo","selectorHorizonte","tituloMonitoreo","detalleMonitoreo","textoEstadoMonitoreo","barraProgresoMotor","pasoSearch","pasoValidate","pasoPrepare","pasoExecute","botonCancelarMonitoreo","nombreMercado","estadoDatos","precioActual","contadorTicks","ultimoDigito","horaActualizacion","listaUltimosDigitos","panelSenal","estadoPrediccion","tituloPrediccion","valorPrediccion","puntajeSenal","barraPuntaje","cuentaRegresiva","mensajeOperacion","listaMotivos","tendencia","detalleTendencia","rsi","detalleRsi","momentum","detalleMomentum","volatilidad","detalleVolatilidad","estadisticaIntentos","estadisticaAciertos","estadisticaFallos","estadisticaPrecision","precisionObservada","botonReiniciarEstadisticas","botonVoz","selectorVoz","velocidadVoz","valorVelocidad","botonProbarVoz","registroActividad","botonLimpiarRegistro","capsulaSenal","estadoCapsula","valorCapsula","detalleCapsula"].forEach(id=>U[id]=$(id));
const S={connected:false,on:false,symbol:"1HZ100V",strategy:"rise_fall",mode:"fast",horizon:"10s",prices:[],digits:[],ticks:0,last:null,pip:2,lastScan:0,snap:null,opp:null,active:null,stats:{}};let toastTimer,countTimer;
const text=(e,v)=>e&&(e.textContent=String(v)),log=(m,c="")=>{let p=document.createElement("p");p.textContent=`[${new Date().toLocaleTimeString("es-SV")}] ${m}`;p.className=c;U.registroActividad?.prepend(p)},key=()=>[S.symbol,S.strategy,S.mode,S.horizon].join("|"),stat=()=>S.stats[key()]??=( {tests:0,ok:0,fail:0});
function renderStats(){let x=stat(),p=x.tests?x.ok/x.tests*100:null;text(U.estadisticaIntentos,x.tests);text(U.estadisticaAciertos,x.ok);text(U.estadisticaFallos,x.fail);text(U.estadisticaPrecision,p==null?"NO DATA":`${p.toFixed(1)}%`);text(U.precisionObservada,`${x.ok} / ${x.tests} TESTS`)}
function renderEngine(){text(U.textoEstadoMotor,S.on?"ON":"OFF");U.estadoMotor?.classList.toggle("engine",S.on);U.botonEncenderMotor.textContent=S.on?"STOP ENGINE":"START ENGINE";let min=S.mode==="complete"?CFG.minComplete:CFG.minFast;U.botonPrediccion.disabled=!S.connected||!S.on||S.prices.length<min;[U.selectorEstrategia,U.selectorMercado,U.selectorModo,U.selectorHorizonte].forEach(e=>e.disabled=S.on)}
function conn(st,label){S.connected=st==="live";text(U.textoEstadoConexion,label);U.estadoConexion.className=`status-pill ${st}`;U.botonConectar.disabled=st==="live"||st==="connecting";U.botonDesconectar.disabled=st!=="live";U.botonEncenderMotor.disabled=st!=="live";if(!S.connected&&S.on)stop(false)}
function start(){if(!S.connected)return;S.on=true;engine2.reset();renderEngine();text(U.mensajeControl,"Dos motores y consenso activos.");voice.speak(`Motor encendido. ${MARKETS[S.symbol]}. Buscando oportunidad.`);log("Motor 1, Motor 2 y Consenso activados.","ok")}
function stop(speak=true){S.on=false;S.active=null;clearInterval(countTimer);engine2.reset();renderEngine();if(speak)voice.speak("Motor apagado.")}
function reset(){S.prices=[];S.digits=[];S.ticks=0;S.last=null;S.active=null;text(U.precioActual,"--");text(U.contadorTicks,0);text(U.ultimoDigito,"--");U.listaUltimosDigitos.innerHTML="";renderEngine()}
function tick(t){if(t.symbol!==S.symbol)return;let f=t.price.toFixed(t.pipSize),d=Number(f.match(/(\d)(?!.*\d)/)?.[1]);S.last=t.price;S.pip=t.pipSize;S.ticks++;S.prices.push(t.price);if(S.prices.length>CFG.maxPrices)S.prices.shift();if(Number.isInteger(d)){S.digits.push(d);if(S.digits.length>CFG.maxDigits)S.digits.shift()}text(U.precioActual,f);text(U.contadorTicks,S.ticks);text(U.ultimoDigito,d);text(U.horaActualizacion,new Date(t.epoch*1000).toLocaleTimeString("es-SV"));text(U.estadoDatos,"LIVE DATA");text(U.estadoMemoria,S.prices.length);digits();evaluate(t.price,d);if(S.on)scan(false)}
function digits(){U.listaUltimosDigitos.innerHTML="";S.digits.slice(-20).forEach((d,i,a)=>{let x=document.createElement("span");x.className="digit"+(i===a.length-1?" current":"");x.textContent=d;U.listaUltimosDigitos.appendChild(x)})}
function scan(force=false){let min=S.mode==="complete"?CFG.minComplete:CFG.minFast;if(S.prices.length<min)return null;let now=Date.now();if(!force&&now-S.lastScan<CFG.scanMs)return null;S.lastScan=now;S.snap=snapshot(S.prices,S.digits,S.mode);S.opp=explore(S.strategy,S.snap);renderIndicators();renderScore();engine2.update(S.opp,S.snap);engine2.receive(S.opp,S.snap);return S.opp}
function renderIndicators(){let s=S.snap;text(U.tendencia,s.trend.direction);text(U.detalleTendencia,`${s.trend.percent.toFixed(4)}%`);text(U.rsi,s.rsi==null?"--":s.rsi.toFixed(1));text(U.detalleRsi,s.rsiState);text(U.momentum,s.momentum.direction);text(U.detalleMomentum,`${s.momentum.percent.toFixed(4)}%`);text(U.volatilidad,`${s.volatility.percent.toFixed(4)}%`);text(U.detalleVolatilidad,s.volatility.level)}
function renderScore(){text(U.puntajeSenal,`${S.opp.score}/100`);U.barraPuntaje.style.width=`${S.opp.score}%`;text(U.mensajeOperacion,S.opp.direction==="WAIT"?"Motor 1 continúa buscando.":`Motor 1 detectó ${visual(S.opp)}.`)}
function reasons(o){U.listaMotivos.innerHTML="";[...(o.reasons||[]),...(o.warnings||[]).map(x=>`⚠ ${x}`)].forEach(t=>{let li=document.createElement("li");li.textContent=t;U.listaMotivos.appendChild(li)})}
function panel(o,phase){U.panelSenal.className=`card signal-card ${phase==="CONFIRMED"?"confirmed":"prepare"}`;text(U.estadoPrediccion,phase);text(U.tituloPrediccion,phase==="CONFIRMED"?"Consenso confirmado":phase==="REVALIDATING"?"Motor 2 revalidando":"Posible oportunidad");text(U.valorPrediccion,visual(o));text(U.puntajeSenal,`${o.consensusScore||o.score}/100`);U.barraPuntaje.style.width=`${o.consensusScore||o.score}%`;reasons(o)}
function toast(type,state,value,detail,ms=4000){clearTimeout(toastTimer);U.capsulaSenal.className=`signal-toast ${type} visible`;text(U.estadoCapsula,state);text(U.valorCapsula,value);text(U.detalleCapsula,detail);toastTimer=setTimeout(()=>U.capsulaSenal.classList.remove("visible"),ms)}
function validatorState(d){let title={IDLE:"SEARCHING ENTRY",PREPARE:"PREPARE",REVALIDATING:"REVALIDATING",EXECUTING:"EXECUTE NOW",RESULT:"RESULT",CANCELLED:"CANCELLED"}[d.state],p={IDLE:18,PREPARE:68,REVALIDATING:86,EXECUTING:100,RESULT:100,CANCELLED:0}[d.state]||0;text(U.textoEstadoMonitoreo,d.state);text(U.tituloMonitoreo,title);text(U.detalleMonitoreo,d.message);U.barraProgresoMotor.style.width=`${p}%`;U.botonCancelarMonitoreo.hidden=!["PREPARE","REVALIDATING"].includes(d.state)}
function prepare({opportunity:o}){panel(o,"PREPARE");toast("prepare","PREPARE",visual(o),"Señal bloqueada. Prepare el bot.",5000);voice.prepare(o)}
function revalidate({opportunity:o}){panel(o,"REVALIDATING");toast("prepare","REVALIDATING",visual(o),"Motor 2 y Consenso revisando.",3000);voice.revalidate(o)}
function confirm({opportunity:o}){S.active={o,price:S.last,tick:S.ticks,time:Date.now(),done:false};panel(o,"CONFIRMED");toast("confirmed","EXECUTE NOW",visual(o),"Los dos motores coinciden.",6000);voice.confirm(o);countdown(o)}
function cancel({opportunity:o,reason}){S.active=null;clearInterval(countTimer);toast("cancelled","CANCELLED",o?visual(o):"WAIT",reason,3200);voice.cancel()}
function result({success,opportunity:o}){clearInterval(countTimer);let x=stat();x.tests++;success?x.ok++:x.fail++;renderStats();text(U.estadoPrediccion,success?"SUCCESS":"FAILED");text(U.tituloPrediccion,success?"Predicción acertada":"Predicción fallida");text(U.valorPrediccion,visual(o));text(U.cuentaRegresiva,success?"✓":"×");voice.result(success);S.active=null}
function seconds(){return S.horizon==="1m"?60:S.horizon==="2m"?120:S.horizon==="5m"?300:10}
function countdown(o){clearInterval(countTimer);let n=o.strategy==="rise_fall"?seconds():CFG.timing[o.strategy].execute;text(U.cuentaRegresiva,n);countTimer=setInterval(()=>{n--;text(U.cuentaRegresiva,Math.max(0,n));if(n<=0)clearInterval(countTimer)},1000)}
function evaluate(price,digit){let s=S.active;if(!s||s.done)return;let o=s.o,t=S.ticks-s.tick;if(o.strategy==="even_odd"&&t>=1)finish(o.direction==="EVEN"?digit%2===0:digit%2!==0,{digit});else if(o.strategy==="over_under"&&t>=1)finish(o.direction==="OVER"?digit>=5:digit<=4,{digit});else if(o.strategy==="match"&&t>=1){if(digit===o.metadata.digit)finish(true,{digit,t});else if(t>=5)finish(false,{digit,t})}else if(o.strategy==="rise_fall"&&Date.now()-s.time>=seconds()*1000)finish(o.direction==="RISE"?price>s.price:price<s.price,{start:s.price,end:price})}
function finish(ok,details){S.active.done=true;engine2.result(ok,details)}
function manual(){let o=scan(true);if(!o)return;toast(o.direction==="WAIT"?"cancelled":"prepare","MANUAL ANALYSIS",visual(o),manualText(o),4800);reasons(o);voice.speak(manualText(o))}
async function init(){await voice.init();U.selectorVoz.innerHTML="";voice.voices.forEach(v=>{let o=document.createElement("option");o.value=`${v.name}|${v.lang}`;o.textContent=`${v.name} · ${v.lang}`;U.selectorVoz.appendChild(o)});renderStats();renderEngine();text(U.nombreMercado,MARKETS[S.symbol]);log(`Trading Analyst Pro MR V${VERSION} listo.`,"ok")}
U.botonConectar.onclick=()=>derivAPI.connect(S.symbol);U.botonDesconectar.onclick=()=>{stop(false);derivAPI.disconnect()};U.botonEncenderMotor.onclick=()=>S.on?stop():start();U.botonPrediccion.onclick=manual;U.selectorMercado.onchange=()=>{S.symbol=U.selectorMercado.value;text(U.nombreMercado,MARKETS[S.symbol]);reset();renderStats();if(S.connected)derivAPI.changeSymbol(S.symbol)};U.selectorEstrategia.onchange=()=>{S.strategy=U.selectorEstrategia.value;renderStats()};U.selectorModo.onchange=()=>{S.mode=U.selectorModo.value;renderStats()};U.selectorHorizonte.onchange=()=>{S.horizon=U.selectorHorizonte.value;renderStats()};U.botonCancelarMonitoreo.onclick=()=>engine2.cancel("Cancelada manualmente.");U.botonVoz.onclick=()=>text(U.botonVoz,voice.toggle()?"🔊":"🔇");U.selectorVoz.onchange=()=>voice.select(U.selectorVoz.value);U.velocidadVoz.oninput=()=>{voice.rate=Number(U.velocidadVoz.value);text(U.valorVelocidad,`${voice.rate.toFixed(2)}x`)};U.botonProbarVoz.onclick=()=>voice.speak("Asistente de voz funcionando. Matches se pronuncia coincidencia.");U.botonReiniciarEstadisticas.onclick=()=>{S.stats[key()]={tests:0,ok:0,fail:0};renderStats()};U.botonLimpiarRegistro.onclick=()=>U.registroActividad.innerHTML="";
derivAPI.on("state",d=>conn(d.state,d.label));derivAPI.on("tick",tick);derivAPI.on("log",d=>log(d.message,d.level));derivAPI.on("error",d=>log(d.message,"error"));engine2.on("state",validatorState);engine2.on("prepare",prepare);engine2.on("revalidate",revalidate);engine2.on("confirm",confirm);engine2.on("cancel",cancel);engine2.on("result",result);init();
